version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../:/workspaces/DIGDIR-embedding-av-offentlige-dokumenter

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # this makes it break in our scenario for some reason
    # network_mode: bridge

    depends_on:
      - mariadb

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
  # mysql:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mysql
  #     MYSQL_USER: mysql
  #     MYSQL_PASSWORD: mysql
  #   ports:
  #     - "3306:3306"
  #   volumes: 
  #     - ../db:/docker-entrypoint-initdb.d
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: mariadb
    ports:
      - "3306:3306"
    volumes: 
      - ../db:/docker-entrypoint-initdb.d
